### ISSUE TITLE
["CONNECTING", "OPEN", "CLOSING", "CLOSED"] static consts is not defined in WebSocket constructor 

### ISSUE THREAD

**Issue by llevkin** [knowledgecode/WebSocket-for-Android#32] opened 2016-11-22 09:07 UTC
This consts defined in prototype only, and it break capability for some WebSocket librarys..

**Comment by knowledgecode** [comment] 2016-11-22 14:08
Thanks for pointing it out. I'll take a look.

**Comment by knowledgecode** [comment] 2016-11-22 15:43
Just fixed it, and released as v0.12.1. Please make sure the problem is fixed.

**Comment by llevkin** [comment] 2016-12-15 12:55
Yes, all looks fine now. Thank you!

**Closed** 2016-12-15 13:55 UTC
